[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "ops.ecris"
description = "Data collection and general tools for various ECRIS projects."
requires-python = ">=3.11"
authors = [
    {name = "Jessica Rehak", email = "rehak@lbl.gov"}
]
dynamic = ["version"]
dependencies = [
    "numpy",
    "matplotlib",
    "pandas",
    "telnetlib3",
    "labjack-ljm",
    "websockets",
    "h5py",
    "pyvisa (>=1.16.1,<2.0.0)",
    "pyvisa-py (>=0.8.1,<0.9.0)",
    "pyusb (>=1.3.1,<2.0.0)",
    "pyzmq (>=26.0.0)",
]

[tool.poetry]
version = "0.2.2"
packages = [ { include = "ops/ecris" } ]

[tool.poetry.group.dev.dependencies]
rich = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
ruff = "*"
pyright = "*"

[tool.pytest.ini_options]
pythonpath = [ 
    "." 
    ]
addopts = [
    "--cov=ops/ecris",
    "--cov-report=term-missing", 
    "--cov-report=xml",          
]

# Tool settings
[tool.ruff]
target-version = "py311"
line-length = 99
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "dist",
    "build",
]
src = ["."]

[tool.ruff.lint]
select = ["E", "W", "F", "I"]

[tool.ruff.lint.isort]
known-first-party = ["ops.ecris"]

[tool.pyright]
reportUnusedImports = "none"
pythonVersion = "3.11"
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "dist",
    "build",
]
